### ISSUE TITLE
ZXHN H168N V3.5 

### ISSUE THREAD

**Issue by minanagehsalalma** [mkst/zte-config-utility#11]
@mkst  hi mate, how you doing.

any idea how can i decrypt the ZXHN H168N V3.5  config 
![image](https://user-images.githubusercontent.com/20546638/101381977-16a94380-38c0-11eb-8b33-72bd4e72f6ec.png)

also using router pass view tool(a closed source one) is able to decrypt the older version of it V3.1. tested on two routers of it and it gave me this output
 
```
Encrypted Data Start Position: 227
Encryption Algorithm: AES-128
Encryption Key: 34303263333864653339626564363635
Compression: zlib / deflate

```
and
 
```
Encrypted Data Start Position: 227
Encryption Algorithm: AES-128
Encryption Key: 4772574D33487A264C54767A26665E39
Compression: zlib / deflate

```
also someone told me

>the encryption algorithm was changed to AES-256-CBC and key and iv are derived from MAC, SerialNumber and EncryKey.

>snprintf(&g_keySeed, 65, "%s%sMcd5c46e", EncryKey, SN);
snprintf(&g_ivSeed, 65, "G21b667b%s%s", MAC, EncryKey);

> sha256(key_seed, key_seed_len, &aes_key);
 sha256(iv_seed, iv_seed_len, &aes_iv);

with out telling me what's that encrykey and didn't reply again.

[ZXHN H168N V3.5.zip](https://github.com/mkst/zte-config-utility/files/5654136/ZXHN.H168N.V3.5.zip)

**Comment by snowsquizy** [comment]
With the testing I did with the H268A, the CRC as 0 means you are using the wrong type to encode the xml back to bin.
Not sure about the key required or how to get it

**Comment by minanagehsalalma** [comment]
> With the testing I did with the H268A, the CRC as 0 means you are using the wrong type to encode the xml back to bin.

@snowsquizy oh thanks , but i can't decode it in the first place to encode it back ;|

> Not sure about the key required or how to get it

i am sure that's in the firmware lib files ..... i tried IDA on it but couldn't know how to use it ;

**Comment by kies83** [comment]
Hey dear how u got this firmware from v3.5 @minanagehsalalma @snowsquizy

**Comment by vido89** [comment]
what IV is used by default in ZTE utility ?

**Comment by minanagehsalalma** [comment]
@811Alex 

Thanks a lot for the heads up alex , you can join me and alvi (kies83) on our research on this on discord if you want.

you seem to have great knowledge about this.

there is another way to solve , work this out. 
mostly by emulating the firmware , i  but i don't know how to do it.

**Comment by kies83** [comment]
Qemu or chroot will be used! For emulating Firmware ... Hope alex Knows!

**Comment by minanagehsalalma** [comment]
> Qemu or chroot will be used! For emulating Firmware ... Hope alex Knows!

Qemu for sure 

check this out sure it will help i have previously asked them to add support for the router and they did 
https://github.com/qilingframework/qiling

**Comment by minanagehsalalma** [comment]
@kies83 Yooooo mate
