### ISSUE TITLE
[FEATURE] ZTE ZXHN F670 with telnet root accses 

### ISSUE THREAD

**Issue by man0eul3r** [mkst/zte-config-utility#117]
I would like the ZTE F670 router to be supported

Telnet are open and I can access root user. I can download telnet file like cspd, dataprotocol and etc… but don’t know to use it.

Can someone help me decrypt the config.bin file,?

this my file on telnet

https://drive.google.com/drive/folders/1GyQrkNc6WXQoICSP4wMUzigPTtmn4fpW?usp=sharing

i will pay/donate in your paypal if succses

**Comment by Merul02** [comment]
> I would like the ZTE F670 router to be supported
> 
> Telnet are open and I can access root user. I can download telnet file like cspd, dataprotocol and etc… but don’t know to use it.
> 
> Can someone help me decrypt the config.bin file,?
> 
> this my file on telnet
> 
> https://drive.google.com/drive/folders/1GyQrkNc6WXQoICSP4wMUzigPTtmn4fpW?usp=sharing
> 
> i will pay/donate in your paypal if succses



bisa , saya perlu serial number ( SN ONT ) & mac address nya kirim ke telegram saya , nanti saya eksekusi. https://t.me/thetanozz

**Comment by happyhacks** [comment]
Checkout #118 - since you already posted on re.se. I have put up an answer there.
