### ISSUE TITLE
ZXHN H267N router error

### ISSUE THREAD

**Issue by skorokithakis** [mkst/zte-config-utility#18]
When trying to decrypt the `config.bin` for ZXHN H267N, I get the following error:

```
Traceback (most recent call last):
  File "examples/decode.py", line 75, in <module>
    main()
  File "examples/decode.py", line 63, in main
    infile = zcu.encryption.aes_decrypt(infile, key, is_digi)
  File "/tmp/zte-config-utility/zcu/encryption.py", line 44, in aes_decrypt
    decrypted_data.write(aes_cipher.decrypt(encrypted_data.read()))
  File "/tmp/zte-config-utility/env/lib/python3.8/site-packages/pycryptodomex-3.10.1-py3.8-linux-x86_64.egg/Cryptodome/Cipher/_mode_ecb.py", line 196, in decrypt
    raise ValueError("Data must be aligned to block boundary in ECB mode")
```

Unfortunately, I'm not sure what could have led to unaligned data. I can send you the `config.bin` if there's a private way to do that.

**Comment by 811Alex** [comment]
It's always useful to know what command you used, too. If you want me to take a look when I have the time, just tell me where I can contact you. I can't guarantee anything and you should know that config.bin has some sensitive info in it.

**Comment by skorokithakis** [comment]
I ended up finding the password in a forum, but I'd be glad to send you the config file (I think I still have it). You can contact me hi@stavros.io if you like!

**Comment by 811Alex** [comment]
Is the one you found listed [here](https://github.com/mkst/zte-config-utility/blob/master/zcu/known_keys.py)?

**Comment by skorokithakis** [comment]
IIRC no, I remember looking. I can get you the password later if you want to add it.

**Comment by 811Alex** [comment]
If it's not there, then that would help, yeah!
It would also help if you could provide the exact signature, along with it.
You can get that by using:
```sh
python3 examples/signature.py <your config.bin>
```

**Comment by skorokithakis** [comment]
The signature is:

```
12:24:29 $ python3 signature.py ~/Downloads/Sync/config.bin 
ZXHN H267N V1.0
```

**Comment by skorokithakis** [comment]
So it looks like the password is `$Extra,ODP0ptiOns$987%`, but this isn't a password issue, it crashes because of an alignment issue. It doesn't proceed past the first password tried.

**Comment by 811Alex** [comment]
I'm fairy certain this is not your config.bin encryption key, but your root user password. If you're using the latest version, it should have said it's the wrong key though, so maybe that's something worth taking a look at. I think I'll just throw you an email for the config.bin, so I can run some tests.

**Comment by skorokithakis** [comment]
Ah, yes, I thought the two were the same, sorry. I've sent you my `config.bin` in case it helps, thanks!

**Comment by 811Alex** [comment]
Could you try using your router's serial number instead of a key (with the ``--serial`` parameter)?
_or send it to my email if you want me to try instead_
