### ISSUE TITLE
Add support for F601

### ISSUE THREAD

**Issue by kramwell** [mkst/zte-config-utility#19]
Can you add support for F601 model please? I have this device if you need information.

*specifically for DiGi Mobil

Thanks

**Comment by 811Alex** [comment]
**Assuming you've tried what the readme says and nothing worked**, I could give it a try, but can't guarantee anything. Couple of questions first, though:
- Are you willing to share information like your config.bin? (in private chat, not here, config.bin has some sensitive info in it)
- Do you have access to your router's file system? (ssh/telnet/ftp/serial)
