### ISSUE TITLE
ERORR Add Support For ZTE ZXHN H168N V 2.2

### ISSUE THREAD

**Issue by kies83** [mkst/zte-config-utility#20]
I Just used your git for decrypting my config.bin but cannot find the key i also i have accesss to telnet and tapgram file and i also have mdsum of it THat is d0e615736322e6bc91fdb4e044bcdb20      .. i also used the the first 16 digits of hex but its incorrect ..( d0e615736322e6bc )..eg  i want to decrypt my config for isp username and passworsd.. located inside the file..

**Comment by kies83** [comment]
@mkst @811Alex

**Comment by kies83** [comment]
@mkst @811Alex  Dear plz Help me out to figure out this issue...

**Comment by 811Alex** [comment]
Let's start with the basics, did you try with the ``--try-all-known-keys`` parameter and if so, can you share the exact command you used and the output?

**Comment by kies83** [comment]
Thanks for your Response.. i tried all known keys value .. but failed i didn't know how i can get key for decryption..

**Comment by kies83** [comment]
My model is not in support list and also There is no relative info placed on internet..

**Comment by 811Alex** [comment]
Alright, well honestly, this probably isn't really an issue with this tool itself. However, it would still be nice to add an extra key if we can. If you would like to try a few more things, personally I'd rather continue in PMs somewhere, either if you find my discord or if you tell me where I can reach you. Up to you and no guarantees whatsoever.

**Comment by kies83** [comment]
Yes this is not software issue.. Wheather it's decryption will be beneficial for everyone who has same model number  .. i don't have yours discord or any other account where i or u can text me.. !

**Comment by 811Alex** [comment]
In that case, I think the only way forward would be for you to find a way to attach your tagparam_m file. It needs to be the exact same one, so either make sure that it gives the same md5sum as the original on the router or use ftp if possible. I can't ask you to post your config.bin publicly, since that contains some sensitive info, so you'd have to try any keys, we _might_ come up with, yourself.

That is all ofc assuming this is not user error. You still haven't posted the exact command you used and output, as I asked earlier.

**Comment by kies83** [comment]
I am attaching a tapgram file from router.. 

https://drive.google.com/file/d/1lZUGuLuvI7XQ3ubDnnahn03C4eSn2DZd/view?usp=drivesdk      


Kindly take a view on it .. it's md5 sum is 

d0e615736322e6bc91fdb4e044bcdb20

**Comment by kies83** [comment]
My discord username is alvi.guy#6127 

Feel free to pm me there.. i would like to talk you..

**Comment by kies83** [comment]
@811Alex Dear i am searching for the keys to decrypt my config.bin file and i also have tapgram file and cspd file . I hope it will be helpful for others..

**Comment by 811Alex** [comment]
@kies83 has confirmed that the key ``Q#Zxn*x3kVLc`` works and the re-encoded file (with no changes) is identical to the original.
I'll make a PR in a bit.

**Comment by kies83** [comment]
@811Alex WELL DEAR . THAT'S GREAT 
YOU NEED TO ADD SUPPORT OF THIS MODEL IN YOUR TOOL..

**Comment by 811Alex** [comment]
that's what the PR part means ;)
