### ISSUE TITLE
zte zxhn h288a

### ISSUE THREAD

**Issue by prografor** [mkst/zte-config-utility#33]
decrypt zte zxhn h288a

**Comment by benghanou** [comment]
Please help me decrypt the router ZTE H288A V1.1.0
If you need a backup to work on it, please contact me by e-mail,
benghanou63@gmail.com
thank you

**Comment by benghanou** [comment]
please help me decrypt ZTE F680 all virsion 
If you need a backup to work on it, please contact me by e-mail,
benghanou63@gmail.com
thank you
