### ISSUE TITLE
Waiting for H298A V9 support

### ISSUE THREAD

**Issue by sivasspor** [mkst/zte-config-utility#38]
**Description of new feature**
 I would like the H298A V9 router to be supported

**Describe alternatives you've considered**
C:\Users\Yusuf\Desktop\zte-config-utility-master>py examples/decode.py --serial ZTC094AD61Axxx config.bin config.xml
Signature: H298A V9
Failed! Trying again, with signature: H298AV9
Malformed decrypted payload, likely you used the wrong key!

**Comment by aycanuAydemir** [comment]
+1

**Comment by Aokromes** [comment]
duplicate of https://github.com/mkst/zte-config-utility/issues/31

**Comment by akahmet** [comment]
Not an unpacker but you can root your router with this script.

https://github.com/gibirnet/H298A-V9-Rooter

**Comment by mkst** [comment]
closing as dupe of https://github.com/mkst/zte-config-utility/issues/31
