### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by pawellupicki** [mkst/zte-config-utility#39]
**Description of new feature**
e.g. I would like the ZTE 1234 XYZ v2.5 router to be supported

**Describe alternatives you've considered**
e.g. I have tried using --payload xxx but I get the following error < error >

**Additional context**

**Attach config.bin for your device**
Optional, but will help anyone trying to add support for the device.

**Comment by mkst** [comment]
Looks to have been opened in error.
