### ISSUE TITLE
help with zte f670l model

### ISSUE THREAD

**Issue by foolbaby** [mkst/zte-config-utility#40]
i have no luck with model ZTE F670L,
anyone can help to show user and pass my pppoe dial ? thanks
[https://www.mediafire.com/file/y3ecelze5tzktkb/config_f670.bin/file](url)

**Comment by pcontezini** [comment]
Same here, would love to use it in bridge mode and never worry about it again.

**Comment by macydnah** [comment]
> Just so you know and for future reference, is possible to encrypt/decrypt the config.bin for F670L router.
>
> As commented by @zhanshi123 in #66 
>> Your key will be the ONT serial number (ZTEGXXXXXXXX - get only last 8 hex characters in uppercase) + MAC address of your ONT (from right to left).
>
> But rather than using the scripts from this repo —at least until payload type 6 gets supported— using the scripts from @ludufre\'s [fork](https://github.com/ludufre/zte-config-utility).

_Originally posted in https://github.com/mkst/zte-config-utility/issues/52#issuecomment-1996074392_

**Comment by ludufre** [comment]
For the passwords dump: https://zte-hack.web.app/
