### ISSUE TITLE
[FEATURE] ZTE F670L FV9 Support

### ISSUE THREAD

**Issue by zainarbani** [mkst/zte-config-utility#52]
**Description of new feature**
I would like the ZTE F670L v9 router to be supported

**Describe alternatives you've considered**
I have tried using examples/decode.py  config.bin config.xml but I get the following error 
< AssertionError on "zcu.zte.read_header(infile)" >

**Additional context**
Im not sure how this works but similiar utility tools check for this [headers](https://github.com/TommyLau/ztecfg/blob/158cc37f01e82d9287017a185e60e09816773de9/ztecfg.py#L31)

**Attach config.bin for your device**
I can send it if needed, also got telnet access.

**Comment by zainarbani** [comment]
Using 'Felis-Sapiens' script get the following error:
`
python test.py config.bin conf.xml
first version header magic:    0x99999999, 0x44444444, 0x55555555, 0xAAAAAAAA
second version header offset:  0x14
third version header offset:   0x40000000
b''
ERROR: failed to read the third version header
Traceback (most recent call last):
  File "C:\Users\zain\Downloads\Compressed\test.py", line 195, in <module>
    main()
  File "C:\Users\zain\Downloads\Compressed\test.py", line 192, in main
    read_config(args.infile, args.outfile, args.key)
  File "C:\Users\zain\Downloads\Compressed\test.py", line 101, in read_config
    ver_header_3 = struct.unpack('>2H5I', ver_header_3)
struct.error: unpack requires a buffer of 24 bytes
`

**Comment by zainarbani** [comment]
Another way using telnet access:
https://github.com/zainarbani/ztelnet

Tested on ZTE F670L FV9

**Comment by zhanshi123** [comment]
> Another way using telnet access:
> https://github.com/zainarbani/ztelnet
> 
> Tested on ZTE F670L FV9

Hi, what is the exact procedure you followed with this tool. I have a ZTE F660 v9 router, but this tool is not working for that.

**Comment by zainarbani** [comment]
> > Another way using telnet access:
> > https://github.com/zainarbani/ztelnet
> > Tested on ZTE F670L FV9
> 
> Hi, what is the exact procedure you followed with this tool. I have a ZTE F660 v9 router, but this tool is not working for that.

You got telnet access?

**Comment by zhanshi123** [comment]
> > > Another way using telnet access:
> > > https://github.com/zainarbani/ztelnet
> > > Tested on ZTE F670L FV9
> > 
> > Hi, what is the exact procedure you followed with this tool. I have a ZTE F660 v9 router, but this tool is not working for that.
> 
> You got telnet access?

I mean the tool you have mentioned above (ztelnet). It's failing 😐. So no telnet access. I asked for the procedure you followed with that tool.

**Comment by zainarbani** [comment]
> > > > Another way using telnet access:
> > > > https://github.com/zainarbani/ztelnet
> > > > Tested on ZTE F670L FV9
> > > 
> > > 
> > > Hi, what is the exact procedure you followed with this tool. I have a ZTE F660 v9 router, but this tool is not working for that.
> > 
> > 
> > You got telnet access?
> 
> I mean the tool you have mentioned above (ztelnet). It's failing 😐. So no telnet access. I asked for the procedure you followed with that tool.

Not sure, failing like what?
send log

**Comment by zainarbani** [comment]
![bruh](https://user-images.githubusercontent.com/31644731/201001415-11c5e89c-9616-4fb3-8099-8154700fe90b.png)

output should be like this if your router supported

**Comment by zhanshi123** [comment]
> ![bruh](https://user-images.githubusercontent.com/31644731/201001415-11c5e89c-9616-4fb3-8099-8154700fe90b.png)
> 
> output should be like this if your router supported

Ah then it is not supported.

**Comment by langit7** [comment]
to enable telnet you can use this python project
https://github.com/douniwan5788/zte_modem_tools

**Comment by macydnah** [comment]
Just so you know and for future reference, is possible to encrypt/decrypt the config.bin for F670L router.

As commented by @zhanshi123 in issue #66 
> Your key will be the ONT serial number (ZTEGXXXXXXXX - get only last 8 hex characters in uppercase) + MAC address of your ONT (from right to left).

But rather than using the scripts from this repo —at least until payload type 6 gets supported— using the scripts from @ludufre\'s fork, [here](https://github.com/ludufre/zte-config-utility).

**Comment by ElclarkKuhu** [comment]
to add to @macydnah and @zhanshi123 The key is Last 6 hex characters in uppercase + MAC Address From Right To Left in lowercase

Example: 
Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7
Mac Address: 08:F6:06:D4:38:F4 => f438d406f608
Key: CF4EF6F7f438d406f608

It take me hours to notice, just in case people have the same problem with me

**Comment by zainarbani** [comment]
> > to add to @macydnah and @zhanshi123 The key is Last 6 hex characters in uppercase + MAC Address From Right To Left in lowercase
> > Example: Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7 Mac Address: 08:F6:06:D4:38:F4 => f438d406f608 Key: CF4EF6F7f438d406f608
> > It take me hours to notice that the the mac address supposed to be lowercase, just in case people have the same problem with me
> 
> Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7
> 
> Bro how did you convert CF28772B => CF4EF6F7 I just cant understand that....

Try this:
https://gist.github.com/zainarbani/723d1387bec9e1559de7a1029d08aa91

`python decrypt.py config.bin config.xml --sn ZTEXXXXXXXX --mac xx:xx:xx:xx:xx:xx`

Just put your actual MAC/SN,
This is the same code, just standalone decryptor.

**Comment by JMarcosHP** [comment]
> > > to add to @macydnah and @zhanshi123 The key is Last 6 hex characters in uppercase + MAC Address From Right To Left in lowercase
> > > Example: Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7 Mac Address: 08:F6:06:D4:38:F4 => f438d406f608 Key: CF4EF6F7f438d406f608
> > > It take me hours to notice that the the mac address supposed to be lowercase, just in case people have the same problem with me
> > 
> > 
> > Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7
> > Bro how did you convert CF28772B => CF4EF6F7 I just cant understand that....
> 
> Try this: https://gist.github.com/zainarbani/723d1387bec9e1559de7a1029d08aa91
> 
> `python decrypt.py config.bin config.xml --sn ZTEXXXXXXXX --mac xx:xx:xx:xx:xx:xx`
> 
> Just put your actual MAC/SN, This is the same code, just standalone decryptor.

Thanks bro, It's working for me. Can you provide a tool to reencode?

**Comment by TechySkills** [comment]
um what the sigma... why close this? we need support for a usbbak.cfg format? not a config.bin

**Comment by cybercuate** [comment]
> > > to add to @macydnah and @zhanshi123 The key is Last 6 hex characters in uppercase + MAC Address From Right To Left in lowercase
> > > Example: Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7 Mac Address: 08:F6:06:D4:38:F4 => f438d406f608 Key: CF4EF6F7f438d406f608
> > > It take me hours to notice that the the mac address supposed to be lowercase, just in case people have the same problem with me
> > 
> > 
> > Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7
> > Bro how did you convert CF28772B => CF4EF6F7 I just cant understand that....
> 
> Try this: https://gist.github.com/zainarbani/723d1387bec9e1559de7a1029d08aa91
> 
> `python decrypt.py config.bin config.xml --sn ZTEXXXXXXXX --mac xx:xx:xx:xx:xx:xx`
> 
> Just put your actual MAC/SN, This is the same code, just standalone decryptor.

**_not working_**

Detected signature: F670L
Detected payload type 6
MAC: xxxxxxxxxxxxxxxxxx (yes, I put mac address)
S/N: xxxxxxxxxxxxxxxxxx (yes,I put serial number)
Traceback (most recent call last):
  File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 218, in <module>
    main()
  File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 204, in main
    res, _ = zteCompression.decompress(infile)
  File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 140, in decompress
    aes_header = struct.unpack('>3I', infile.read(12))
struct.error: unpack requires a buffer of 12 bytes

**Comment by Mesier83** [comment]
Totally noob question but
Where I can find the config.xml file?

**Comment by TechySkills** [comment]
You can export the settings of your router by going in Management and
Diagnostics, and then System Management and then you can export afaik
*Regards*
*TechySkills*

**Comment by langit7** [comment]
Some ISP disabled export config
![image](https://github.com/user-attachments/assets/448bbdc0-16ba-4966-b147-4f9d7d5a5736)

**Comment by idcidgf** [comment]
> Some ISP disabled export config ![image](https://private-user-images.githubusercontent.com/20891738/367273506-448bbdc0-16ba-4966-b147-4f9d7d5a5736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYzNTIsIm5iZiI6MTczMDI2NjA1MiwicGF0aCI6Ii8yMDg5MTczOC8zNjcyNzM1MDYtNDQ4YmJkYzAtMTZiYS00OTY2LWIxNDctNGY5ZDdkNWE1NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1MjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzhkZjc4OTdmODdjZjRjNzIxOWJhMTE5OWNlMWJjNTI3MWZiZTlhNjllZDNlOWY2NWY3YTIyZjI2YWRmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeipmsv-1cSrn3BaD_Tif6fAz2AFiy_AssTXEbLg7Ak)

bro same issue. lets connect on telegram and get this thing sorted. @TravelXtreme

**Comment by langit7** [comment]
> > Some ISP disabled export config ![image](https://private-user-images.githubusercontent.com/20891738/367273506-448bbdc0-16ba-4966-b147-4f9d7d5a5736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYzNTIsIm5iZiI6MTczMDI2NjA1MiwicGF0aCI6Ii8yMDg5MTczOC8zNjcyNzM1MDYtNDQ4YmJkYzAtMTZiYS00OTY2LWIxNDctNGY5ZDdkNWE1NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1MjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzhkZjc4OTdmODdjZjRjNzIxOWJhMTE5OWNlMWJjNTI3MWZiZTlhNjllZDNlOWY2NWY3YTIyZjI2YWRmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeipmsv-1cSrn3BaD_Tif6fAz2AFiy_AssTXEbLg7Ak)
> 
> bro same issue. lets connect on telegram and get this thing sorted. @TravelXtreme

Downgrade the firmware and  then add or activate root user, most ISP will randomize admin password.

**Comment by idcidgf** [comment]
> > > Some ISP disabled export config ![image](https://private-user-images.githubusercontent.com/20891738/367273506-448bbdc0-16ba-4966-b147-4f9d7d5a5736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYzNTIsIm5iZiI6MTczMDI2NjA1MiwicGF0aCI6Ii8yMDg5MTczOC8zNjcyNzM1MDYtNDQ4YmJkYzAtMTZiYS00OTY2LWIxNDctNGY5ZDdkNWE1NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1MjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzhkZjc4OTdmODdjZjRjNzIxOWJhMTE5OWNlMWJjNTI3MWZiZTlhNjllZDNlOWY2NWY3YTIyZjI2YWRmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeipmsv-1cSrn3BaD_Tif6fAz2AFiy_AssTXEbLg7Ak)
> > 
> > 
> > bro same issue. lets connect on telegram and get this thing sorted. @TravelXtreme
> 
> Downgrade the firmware and then add or activate root user, most ISP will randomize admin password.

bro i need your help asap. lets connect over telegram

**Comment by langit7** [comment]
> > > > Some ISP disabled export config ![image](https://private-user-images.githubusercontent.com/20891738/367273506-448bbdc0-16ba-4966-b147-4f9d7d5a5736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjYzNTIsIm5iZiI6MTczMDI2NjA1MiwicGF0aCI6Ii8yMDg5MTczOC8zNjcyNzM1MDYtNDQ4YmJkYzAtMTZiYS00OTY2LWIxNDctNGY5ZDdkNWE1NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1MjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzhkZjc4OTdmODdjZjRjNzIxOWJhMTE5OWNlMWJjNTI3MWZiZTlhNjllZDNlOWY2NWY3YTIyZjI2YWRmZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeipmsv-1cSrn3BaD_Tif6fAz2AFiy_AssTXEbLg7Ak)
> > > 
> > > 
> > > bro same issue. lets connect on telegram and get this thing sorted. @TravelXtreme
> > 
> > 
> > Downgrade the firmware and then add or activate root user, most ISP will randomize admin password.
> 
> bro i need your help asap. lets connect over telegram

share your telegram link

**Comment by TechySkills** [comment]
my isp also disabled the export config some months ago by a remote update
of firmware. though i have the admin password by some social engineering.
can i also get ur help?
*Regards*
*TechySkills*

**Comment by aserralta** [comment]
> > > > to add to [@macydnah](https://github.com/macydnah) and @zhanshi123 The key is Last 6 hex characters in uppercase + MAC Address From Right To Left in lowercase
> > > > Example: Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7 Mac Address: 08:F6:06:D4:38:F4 => f438d406f608 Key: CF4EF6F7f438d406f608
> > > > It take me hours to notice that the the mac address supposed to be lowercase, just in case people have the same problem with me
> > > 
> > > 
> > > Serial No: XXXXXX-ZTEGCF28772B => CF4EF6F7
> > > Bro how did you convert CF28772B => CF4EF6F7 I just cant understand that....
> > 
> > 
> > Try this: https://gist.github.com/zainarbani/723d1387bec9e1559de7a1029d08aa91
> > `python decrypt.py config.bin config.xml --sn ZTEXXXXXXXX --mac xx:xx:xx:xx:xx:xx`
> > Just put your actual MAC/SN, This is the same code, just standalone decryptor.
> 
> **_not working_**
> 
> Detected signature: F670L Detected payload type 6 MAC: xxxxxxxxxxxxxxxxxx (yes, I put mac address) S/N: xxxxxxxxxxxxxxxxxx (yes,I put serial number) Traceback (most recent call last): File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 218, in main() File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 204, in main res, _ = zteCompression.decompress(infile) File "C:\Users\cyber\OneDrive\Escritorio\zte-config-utility-master\examples\decrypt.py", line 140, in decompress aes_header = struct.unpack('>3I', infile.read(12)) struct.error: unpack requires a buffer of 12 bytes

Did you find a solution? I had the same issue but I just had to put the S/N all in uppercase
