### ISSUE TITLE
[FEATURE] ZXHN H288A Support

### ISSUE THREAD

**Issue by prografor** [mkst/zte-config-utility#58]
Decryption problem is there a solution zte H288A 
ZXHN H288A V1.1 V1.1.3C4_MARI
H288A V1.1.0_GR5.1T16

![H288A](https://user-images.githubusercontent.com/97105502/209484681-7cf8c395-093d-4594-8da1-ca8d73a0fc91.jpg)

**Comment by rajkosto** [comment]
It's supported. Why open a new issue for this ?
See existing issue: https://github.com/mkst/zte-config-utility/issues/43#issuecomment-1310765601

**Comment by amr1982** [comment]
Fujifilm Camera Firmware Update | How To

**Comment by mkst** [comment]
closing as duplicate.
