### ISSUE TITLE
[FEATURE] ZTE ZXHN F680 Support

### ISSUE THREAD

**Issue by benghanou** [mkst/zte-config-utility#59]
please help me decrypt ZTE F680 all virsion
If you need a backup to work on it ZTE F680 backup https://mega.nz/file/0ioB0JJT#XRp_NClzwL36_JqIdoqUfKlGWvqfRP_Wjmc-TPCJWJ8
thank you

**Comment by mkst** [comment]
Closing as dupe of https://github.com/mkst/zte-config-utility/issues/15
