### ISSUE TITLE
I uploaded the example configuration that is in (/resources/ZXHN H108N V2.5.bin) to my modem and now I can't start the serction

### ISSUE THREAD

**Issue by imanol611** [mkst/zte-config-utility#61]
it presents incorrect credentials before, the credentials I used were admin and the SN and now they no longer work

**Comment by mkst** [comment]
Hmm, not sure that's a good idea. Those resources are just for testing this script, not for uploading to your routers.

That said, there are a couple of potential usernam/password combinations in the [extracted xml](https://github.com/mkst/zte-config-utility/blob/master/resources/ZXHN_H108N_V2.5.xml). Did you try username `admin:admin` or `user:user` ?
