### ISSUE TITLE
F609 key

### ISSUE THREAD

**Issue by Merul02** [mkst/zte-config-utility#70]
localhost:~/zte-config-utility# python3 examples/decode.py resources/config.bin resources/config_.xml
Detected signature: F609
Detected payload type 2
No --key specified or found via signature, and not trying all known keys!
root@localhost:~/zte-config-utility#

please tutorial , how to find or get the right key for ZTE F609 V5.3 , 
I have run the command : 
python3 examples/decode.py --try-all-known-keys resources/config.bin 
 got no results .

[file configuration ](https://drive.google.com/file/d/13d_Sd669scye438AnGESDF7pNzgf5N5G/view?usp=drivesdk)

**Comment by bembenk18** [comment]
untuk key sudah ketemu mas?

**Comment by Merul02** [comment]
iya sudah , penjelasan sya udh cukup detail kok step by step nya . klo mau di bongkar file config.bin nya kirim ke sya , biar sya bantu

**Comment by man0eul3r** [comment]
> sudah detail kok step by step nya . klo mau di bongkar file config.bin nya kirim ke sya , biar sya bantu

untuk zte 670 dgn type payload 5 bisa mas? saya bisa masuk telnet dgn root acses dan download file cspd dll

tp ga bisa nemu key nya

**Comment by man0eul3r** [comment]
Sy sudah coba kombinasi key SN dan Mac dgn beberapa kombinasi huruf besar/kecil di macnya, juga sudah balik urutan angka macnya sesuai postingan dari rekan2 lain tetap tidak bisa 

Apa mungkin F670 berbeda enskripsinya dengan F670L ya
