### ISSUE TITLE
CAN PLEASE SOMEONE HELP ME WITH THIS ONE

### ISSUE THREAD

**Issue by alicedormlol** [mkst/zte-config-utility#74]
This this is the router i have i want  to turn it access point but i cant i can enter to the interface but there is not much setting  and also cant download the firmware
 company name: Orange FUNBOX
country: Morocco

Device Type ZTEH288A
Device Serial No. ZTEEG9KN7704995
Hardware Version ZT-H288A-1.0.0
Software Version ZT_H288A-ma-1.1.0.4
Boot Version V1.0.2
default user and password:
Username : user
Password: OrangeDQFT
Thank You

**Comment by alicedormlol** [comment]
Thanks already find solution

**Comment by alicedormlol** [comment]
ty

**Comment by electrojozef** [comment]
Hey @alicedormlol , can you please help me with the same version.
I'm also from morocco and i cant find how to download the config.bin file.
Thanks.

**Comment by alicedormlol** [comment]
i also can't download the  config.bin only to upload it sad

**Comment by GutzRogue** [comment]
How did you do it  , i'm having currently the same issue  , orange d zbb doesn't let me configure mine

**Comment by alicedormlol** [comment]
> How did you do it , i'm having currently the same issue , orange d zbb doesn't let me configure mine

dkhalt b support

username: support
password: OrangeF830
3la hsab akhir ar9am f mac address 3andak

**Comment by Abdulaziz959** [comment]
did u found something new about config.bin extraction ?

**Comment by EN0514** [comment]
kifach jbdeti lconfig ?

**Comment by ifist5t9t** [comment]
This is the firmware link https://github.com/Freesat-tr/firmware-zte-zxhn-h288a-Orange-maroc 

be carefull

**Comment by buytshop-maker** [comment]
firmware ZTEH288A inwi to version globale plaese

**Comment by GutzRogue** [comment]
What about the inwi support login?

**Comment by Ayoubju** [comment]
Does any of you guys have a copy of this fucking firmware: `H288A V1.2.0P8_INWI` 
I was trying to unlock the router but ended up soft-bricking the motherfucker. Your help is appreciated.
