### ISSUE TITLE
[FEATURE] Add support ZTE H3600 V9

### ISSUE THREAD

**Issue by Harun348** [mkst/zte-config-utility#94]
I would like the ***ZTE H3600 V9*** router to be supported.

![zteh3600v9](https://github.com/mkst/zte-config-utility/assets/82382695/10c751f6-80ac-4da5-a2b9-402d7cc3c873)

**Comment by fagmixy** [comment]
@Harun348  hello you have acces admin to your zte h3600 ?

**Comment by Harun348** [comment]
@fagmixy hi.yes I have access to admin account

**Comment by fagmixy** [comment]
``

> @fagmixy hi.yes I have access to admin account

You have digi h3600 can you help me to have password fro admin please

**Comment by sl1pkn07** [comment]
Hi

same here please

greetings

**Comment by mkst** [comment]
Closing as dupe of https://github.com/mkst/zte-config-utility/issues/76

**Comment by imadknn** [comment]
Can i have a admin password

**Comment by oussachy** [comment]
[p1ezer](https://github.com/p1ezer) Can I have a admin password?

**Comment by registrospikakaka-sys** [comment]
Can I ´ve a admin pass?? thanks!!

**Comment by driversat** [comment]
> Can I ´ve a admin pass?? thanks!!

you have to open the box and connect TTL usb serial cable to pc.
i used this tutorial to get admin password:
https://orca.pet/zteh3600p/
